spring.application.name=computing-power-rental
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.computingpowerrental.entity
mybatis.configuration.map-underscore-to-camel-case=true
jwt.secret-key=computing-power-rental-secret-key-please-change
jwt.access-token-expiration=7200
jwt.refresh-token-expiration=604800
jwt.token-prefix=Bearer
jwt.token-header=Authorization